### ISSUE TITLE
Question to CTF Paper

### ISSUE THREAD

**Issue by Zaby1990** [th30th3rguy/CTFS#1]
Hey other guy,

I found your repository by incident when I was looking for CVEs in the HTB machine "Paper". I stuck at the very beginning and I don't want to spoil to much for me. So I tried not to scroll to much down. But I saw that you say 
"did enumeration to get the backend server which i added to the hosts file to get the wordpress site" and I have no idea what kind of enumeration I can do to find the wordpress site. 
When I looking at the webserver I get the "http server test page". I tried to fuzz the directories of the site but found only the manual. And I tried to fuzz subdomains with vhost, but also didn't found anything.

Can you maybe give me a little hint? 

Thanks a lot.

**Comment by th30th3rguy** [comment]
Hey,
I hope you solved the challenge. I don't use this email more often so I
missed your email. If you need any help, feel free to contact me. I'll be
able to help.

regards
T0g
